#!/bin/zsh

# Launch TUI application in terminal
# Adapted from Omarchy for VV Shell

APP_ID="org.vv.$(basename $1)"

# Запускаем через терминал (foot) с app-id
exec setsid foot --app-id="$APP_ID" -e "$1" "${@:2}"
