name: Bug Report
description: Report a bug or issue with VV OS installer
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Tell us what went wrong
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Boot Arch Live ISO
        2. Run './vv-live-installer.sh'
        3. Select disk '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: The installer should...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Instead, it...
    validations:
      required: true

  - type: dropdown
    id: gpu
    attributes:
      label: GPU Type
      description: What GPU are you using?
      options:
        - NVIDIA dGPU (GTX/RTX)
        - Intel iGPU
        - AMD dGPU
        - AMD APU (Radeon Graphics)
        - Other
    validations:
      required: true

  - type: input
    id: gpu-model
    attributes:
      label: GPU Model
      description: Specific GPU model (e.g., GTX 1650, RX 6700 XT, Intel UHD 620)
      placeholder: GTX 1650
    validations:
      required: false

  - type: dropdown
    id: installation-stage
    attributes:
      label: Installation Stage
      description: At what stage did the error occur?
      options:
        - Live ISO boot
        - vv-live-installer.sh
        - archinstall (base system)
        - install.sh (VV OS components)
        - Post-installation
        - First boot
        - Other
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Copy and paste any relevant error messages or logs
      render: shell
      placeholder: Paste error logs here
    validations:
      required: false

  - type: textarea
    id: system-info
    attributes:
      label: System Information
      description: |
        Run these commands and paste the output:
        ```bash
        uname -a
        lscpu | grep "Model name"
        lspci | grep -E "VGA|3D"
        free -h
        df -h
        ```
      render: shell
      placeholder: Paste system info here
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I searched existing issues and didn't find a duplicate
          required: true
        - label: I used the latest version of VV OS installer
          required: true
        - label: I read the documentation (README.md, docs/)
          required: true
